### PR TITLE
fix: TypeError: Cannot convert a Symbol value to a string

### PR DESCRIPTION
**Pull request by erezarnon**

### CODE REVIEW

**Comment by erezarnon** [comment]
@keithamus quick ping, fixing an exception

**Review by keithamus — APPROVED** [review]

**Comment by erezarnon** [comment]
> Some failing lint errors, if you'd kindly address those I'll merge

Done!

**Comment by erezarnon** [comment]
@keithamus Thank you! Is it worth tagging a release?

**Comment by keithamus** [comment]
Done!

**Pull request merged**
